import { ProjectsItemProps } from "@/types";

export const dataProjects: ProjectsItemProps[] = [
  {
    imgSrc: "/images/reviewnime-1.png",
    title: "ReviewNime",
    desc: "Discover the wonders of the world of anime through ReviewNime a website that lists the best anime films ever made.",
    tags: ["HTML", "CSS", "Javascript"],
    type: "website",
    route: "/reviewnime",
  },
  {
    imgSrc: "/images/pkk-1.png",
    title: "E-PKK",
    desc: "Welcome to E-PKK Kabupaten Nganjuk an innovative web platform specifically designed to help and simplify the process of reporting and managing PKK (Family Empowerment and Welfare) data in Nganjuk Regency.",
    tags: ["Laravel", "Bootstrap"],
    type: "website",
    route: "/epkk",
  },
  {
    imgSrc: "/images/depomayarjaya-1.png",
    title: "Depo Mayar Jaya",
    desc: "Welcome to Depo Mayar Jaya a comprehensive web platform specifically designed to facilitate the management of sales and distribution of products such as gallons of water and LPG.",
    tags: ["Laravel", "Bootstrap"],
    type: "website",
    route: "/depomayarjaya",
  },
  {
    imgSrc: "/images/relive.png",
    title: "ReLive",
    desc: "ReLive is an online mental health consultation platform, designed to provide easy and fast access to users who need psychological help.",
    tags: ["React.js", "Express.js"],
    type: "website",
    route: "/relive",
  },
  {
    imgSrc: "/images/ternakq-beranda.png",
    title: "TernakQ",
    desc: "TernakQ is a poultry farm management platform designed to help farmers manage coops, chickens, feed, financial reports, educational articles, and join discussions through a community forum.",
    tags: ["Laravel Livewire", "Tailwind CSS", "Javascript"],
    type: "website",
    route: "/ternakq",
  },
  {
    imgSrc: "/images/quowrld-page.png",
    title: "Quowr/d",
    desc: "Quowrld is a quote-sharing platform designed to 'capture and immortalize meaningful words' from anyone.",
    tags: ["Next.js", "Supabase", "Tailwind CSS"],
    type: "website",
    route: "/quowrld",
  },
  {
    imgSrc: "/images/kpopulls.png",
    title: "Kpop Pulls",
    desc: "Gacha for my bias, eating instant noodles for a week is not a problem.",
    tags: ["Next.js", "Framer Motion", "Tailwind CSS"],
    type: "website",
    route: "/kpopulls",
  },
  {
    imgSrc: "/images/coderoaster.png",
    title: "Code Roaster",
    desc: "Code issues are my way of expressing that your coding is very poor.",
    tags: ["React.js", "Tailwind CSS", "API OpenAI"],
    type: "website",
    route: "/coderoaster",
  },
  {
    imgSrc: "/images/medmart.png",
    title: "Medmart",
    desc: "Actually, Medmart is one of the design competitions that I participated in via the Instagram platform.",
    type: "design",
    route: "/medmart",
  },
  {
    imgSrc: "/images/eduverse.png",
    title: "EduVerse",
    desc: "EduVerse is a learning application specially designed for high school students.",
    type: "design",
    route: "/eduverse",
  },
];
