import { ProjectsItemProps } from "@/types";

export const dataProjects: ProjectsItemProps[] = [
  {
    imgSrc: "/images/reviewnime-1.png",
    title: "ReviewNime",
    desc: "A complete e-commerce application built with React and Node.js, featuring a secure payment gateway, product filtering, and user authentication.",
    tags: ["HTML", "CSS", "Javascript"],
    link: "https://your-ecommerce-app.com",
    type: "website",
  },
  {
    imgSrc: "/images/pkk-1.png",
    title: "E-PKK Kabupaten Nganjuk",
    desc: "A complete e-commerce application built with React and Node.js, featuring a secure payment gateway, product filtering, and user authentication.",
    tags: ["Laravel", "bootstrap"],
    link: "https://your-ecommerce-app.com",
    type: "website",
  },
  {
    imgSrc: "/images/depomayarjaya-1.png",
    title: "Depo Mayar Jaya",
    desc: "A complete e-commerce application built with React and Node.js, featuring a secure payment gateway, product filtering, and user authentication.",
    tags: ["Laravel", "bootstrap"],
    link: "https://your-ecommerce-app.com",
    type: "website",
  },
  {
    imgSrc: "/images/relive1.png",
    title: "ReLive",
    desc: "A complete e-commerce application built with React and Node.js, featuring a secure payment gateway, product filtering, and user authentication.",
    tags: ["React.js", "Express.js", "Tailwind CSS"],
    link: "https://your-ecommerce-app.com",
    type: "website",
  },
  {
    imgSrc: "/images/justanote.png",
    title: "JustaNote",
    desc: "A complete e-commerce application built with React and Node.js, featuring a secure payment gateway, product filtering, and user authentication.",
    tags: ["React.js", "Tailwind CSS"],
    link: "https://your-ecommerce-app.com",
    type: "website",
  },
  {
    imgSrc: "/images/medmart.png",
    title: "Medmart",
    desc: "A complete e-commerce application built with React and Node.js",
    tags: ["React.js", "Express.js"],
    link: "https://your-ecommerce-app.com",
    type: "design",
  },
  {
    imgSrc: "/images/explorenature-1.png",
    title: "ExploreNature",
    desc: "A complete e-commerce application built with React and Node.js",
    tags: ["React.js", "Express.js"],
    link: "https://your-ecommerce-app.com",
    type: "design",
  },
  {
    imgSrc: "/images/eduverse.png",
    title: "EduVerse",
    desc: "A complete e-commerce application built with React and Node.js",
    tags: ["React.js", "Express.js"],
    link: "https://your-ecommerce-app.com",
    type: "design",
  },
];
